In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout
import math
from sklearn.metrics import mean_squared_error

In [41]:
data= pd.read_csv('/content/drive/MyDrive/IBM_2006-01-01_to_2018-01-01 (1).csv',index_col='Date',parse_dates=['Date'])
data.head()

Open   High    Low  Close    Volume Name
Date                                                 
2006-01-03  82.45  82.55  80.81  82.06  11715200  IBM
2006-01-04  82.20  82.50  81.33  81.95   9840600  IBM
2006-01-05  81.40  82.90  81.00  82.50   7213500  IBM
2006-01-06  83.95  85.03  83.41  84.95   8197400  IBM
2006-01-09  84.10  84.25  83.38  83.73   6858200  IBM

In [45]:
mytrain = data.loc[:'2016', data.columns[1:2]].values
mytest = data.loc['2017':, data.columns[1:2]].values
print(mytrain[0])
print(mytest[0])

[82.55]
[167.87]


In [46]:
sc = MinMaxScaler(feature_range=(0,1))
mytrain_scaled=sc.fit_transform(mytrain)
print(mytrain_scaled)

[[0.06065089]
 [0.06029868]
 [0.06311637]
 ...
 [0.66074951]
 [0.65546633]
 [0.6534235 ]]


In [54]:
len(mytrain_scaled)

2769

In [63]:
I_train = []
o_train = []
for i in range(60,2769):
  I_train.append(mytrain_scaled[i-60:i,0])
  o_train.append(mytrain_scaled[i,0])

In [49]:
I_train = np.array(I_train)
o_train = np.array(o_train)
print(I_train)

[[0.06065089 0.06029868 0.06311637 ... 0.0656523  0.06656805 0.06769513]
 [0.06029868 0.06311637 0.0781206  ... 0.06656805 0.06769513 0.06875176]
 [0.06311637 0.0781206  0.07262609 ... 0.06769513 0.06875176 0.06804734]
 ...
 [0.77042829 0.7611299  0.75887574 ... 0.79289941 0.79430826 0.80198648]
 [0.7611299  0.75887574 0.78071288 ... 0.79430826 0.80198648 0.79923922]
 [0.75887574 0.78071288 0.79099746 ... 0.80198648 0.79923922 0.79888701]]


In [51]:
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(I_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(units=50, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50))
model.add(Dropout(0.2))
model.add(Dense(units=1)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [52]:
model.compile(optimizer= 'adam',loss='mean_squared_error')

In [53]:
model.fit(I_train,o_train,epochs=50,batch_size=32)

Epoch 1/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 15s 137ms/step - loss: 0.0607
Epoch 2/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 10s 139ms/step - loss: 0.0043
Epoch 3/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 8s 110ms/step - loss: 0.0039
Epoch 4/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 11s 115ms/step - loss: 0.0048
Epoch 5/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 12s 140ms/step - loss: 0.0038
Epoch 6/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 10s 130ms/step - loss: 0.0044
Epoch 7/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 9s 109ms/step - loss: 0.0045
Epoch 8/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 11s 120ms/step - loss: 0.0034
Epoch 9/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 9s 139ms/step - loss: 0.0039
Epoch 10/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 7s 109ms/step - loss: 0.0031
Epoch 11/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 12s 133ms/step - loss: 0.0033
Epoch 12/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 8s 130ms/step - loss: 0.0031
Epoch 13/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 8s 123ms/step - loss: 0.0033
Epoch 14/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 11s 143ms/step - loss: 0.0031
Epoch 15/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 7s 110ms/s

In [60]:
model.save('/content/drive/MyDrive/stock_price.h5')

In [64]:
from tensorflow.keras.models import load_model
model = load_model('/content/drive/MyDrive/stock_price.h5')

In [66]:
#60 values
user_input = [83.58746017, 80.34122742, 80.81285462, 82.00291895, 83.29159961, 81.44688209, 80.76357678, 83.80165525, 82.51120409, 82.48569342, 80.65383659, 81.69740582, 82.78338862, 83.37704145, 83.53829805, 80.20374715, 80.42476455, 82.69989097, 83.73417143, 82.95666579, 83.94381372, 82.37856671, 83.60787851, 81.80850007, 82.61239819, 82.06021048, 81.0673498, 83.7835985, 81.74964384, 83.10783276, 80.54146548, 80.49215929, 82.03237911, 81.79802128, 80.93914228, 83.90444224, 83.2143073, 81.31844381, 83.23807452, 83.4603476, 81.85039395, 81.3031393, 80.6351211, 83.65161771, 80.54893536, 82.22940581, 82.50289209, 80.59368723, 83.24620825, 81.77694404, 83.20275117, 83.43996357, 83.38335394, 82.69282925, 80.80822433, 80.30044039, 83.6842126, 82.82960781, 80.12425038, 82.25607533]

#2D array
user_input_array = np.array(user_input).reshape(60, 1)

#down-scale
sc = MinMaxScaler(feature_range=(0,1))
user_scaled = sc.fit_transform(user_input_array)

#3D array
user_scaled = user_scaled.reshape(1, 60, 1)

#predict
pred = model.predict(user_scaled)
print(pred) #down scale output
#up-scale
pred_original = sc.inverse_transform(pred)
print("The stock price is",pred_original[0][0]) #up scaled/original o/p

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 601ms/step
[[0.47949442]]
The stock price is 81.95571
